In [1]:
# ============================================================
# Experiment 02
# To explore major Deep Learning libraries:
# TensorFlow, Keras, MXNet, and JAX
#
# Platform: Google Colab
# ============================================================


# ============================================================
# 1. CHECK PYTHON VERSION
# ============================================================

import sys

print("Python Version:")
print(sys.version)

Python Version:
3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [ ]:
# ============================================================
# 2. INSTALL REQUIRED LIBRARIES
# ============================================================
# TensorFlow and Keras are usually pre-installed in Google Colab.
# JAX is also usually pre-installed.
# MXNet may need installation.

# !pip install mxnet -q

In [ ]:
# # ============================================================
# # 3. IMPORT ALL MAJOR DEEP LEARNING LIBRARIES
# # ============================================================

# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import layers

# import jax
# import jax.numpy as jnp

# import mxnet as mx
# from mxnet import nd, autograd, gluon

# import numpy as np

# print("TensorFlow Version:", tf.__version__)
# print("Keras Version:", keras.__version__)
# print("JAX Version:", jax.__version__)
# print("MXNet Version:", mx.__version__)

In [3]:
# ============================================================
# 3. IMPORT ALL MAJOR DEEP LEARNING LIBRARIES
# ============================================================

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import jax
import jax.numpy as jnp

# import mxnet as mx
# from mxnet import nd, autograd, gluon

import numpy as np

print("TensorFlow Version:", tf.__version__)
print("Keras Version:", keras.__version__)
print("JAX Version:", jax.__version__)
# print("MXNet Version:", mx.__version__)

TensorFlow Version: 2.20.0
Keras Version: 3.13.2
JAX Version: 0.7.2


In [6]:
# ============================================================
# 4. CHECK GPU AVAILABILITY
# ============================================================

print("TensorFlow GPU Available:")
print(tf.config.list_physical_devices('GPU'))

print("\nJAX Devices:")
print(jax.devices())


TensorFlow GPU Available:
[]

JAX Devices:
[CpuDevice(id=0)]


In [7]:
# ============================================================
# 5. TENSORFLOW BASIC OPERATIONS
# ============================================================
# TensorFlow is a popular deep learning library developed by Google.
# It is used for building, training, and deploying machine learning models.

a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("TensorFlow Tensor A:")
print(a)

print("\nTensorFlow Tensor B:")
print(b)

print("\nAddition:")
print(tf.add(a, b))

print("\nMatrix Multiplication:")
print(tf.matmul(a, b))

TensorFlow Tensor A:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

TensorFlow Tensor B:
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

Addition:
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)

Matrix Multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [8]:
# ============================================================
# 6. KERAS SIMPLE NEURAL NETWORK
# ============================================================
# Keras is a high-level API used to build neural networks easily.
# In TensorFlow 2.x, Keras is included inside TensorFlow.

# Dataset for OR gate
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [1]
])

# Create a simple neural network model
model = keras.Sequential([
    layers.Dense(4, activation='relu', input_shape=(2,)),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(X, y, epochs=500, verbose=0)

# Test the model
predictions = model.predict(X)

print("Keras OR Gate Predictions:")
for i in range(len(X)):
    print(X[i], "=>", round(predictions[i][0]))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Keras OR Gate Predictions:
[0 0] => 1
[0 1] => 1
[1 0] => 1
[1 1] => 1


In [9]:
# ============================================================
# 7. JAX BASIC OPERATIONS
# ============================================================
# JAX is a high-performance numerical computing library.
# It supports automatic differentiation and GPU/TPU acceleration.

x = jnp.array([1.0, 2.0, 3.0])

print("JAX Array:")
print(x)

print("\nSquare of Array:")
print(x ** 2)

print("\nSum:")
print(jnp.sum(x))

JAX Array:
[1. 2. 3.]

Square of Array:
[1. 4. 9.]

Sum:
6.0


In [10]:
# ============================================================
# 8. JAX AUTOMATIC DIFFERENTIATION
# ============================================================
# Automatic differentiation is used to calculate gradients.
# Gradients are important for training neural networks.

def function(x):
    return x ** 2 + 3 * x + 5

gradient_function = jax.grad(function)

value = 4.0

print("Function value at x = 4:")
print(function(value))

print("\nGradient value at x = 4:")
print(gradient_function(value))

Function value at x = 4:
33.0

Gradient value at x = 4:
11.0


In [12]:
# # ============================================================
# # 9. MXNET BASIC OPERATIONS
# # ============================================================
# # MXNet is a deep learning framework supported by Apache.
# # It supports symbolic as well as imperative programming.

# a = nd.array([[1, 2], [3, 4]], ctx=ctx)
# b = nd.array([[5, 6], [7, 8]], ctx=ctx)

# print("MXNet Array A:")
# print(a)

# print("\nMXNet Array B:")
# print(b)

# print("\nAddition:")
# print(a + b)

# print("\nMatrix Multiplication:")
# print(nd.dot(a, b))

In [ ]:
# # ============================================================
# # 10. MXNET AUTOMATIC DIFFERENTIATION
# # ============================================================

# x = nd.array([2.0], ctx=ctx)
# x.attach_grad()

# with autograd.record():
#     y = x * x + 3 * x + 5

# y.backward()

# print("Function value:")
# print(y)

# print("\nGradient value:")
# print(x.grad)

In [13]:
# ============================================================
# 11. SIMPLE COMPARISON OF LIBRARIES
# ============================================================

comparison = {
    "Library": ["TensorFlow", "Keras", "JAX", "MXNet"],
    "Developed By": ["Google", "Google / Keras Team", "Google", "Apache"],
    "Main Use": [
        "Deep learning model building and deployment",
        "Easy neural network creation",
        "High-performance numerical computing and research",
        "Deep learning and scalable training"
    ],
    "Difficulty": ["Medium", "Easy", "Medium to Hard", "Medium"]
}

import pandas as pd

df = pd.DataFrame(comparison)
df

,Library,Developed By,Main Use,Difficulty
0,TensorFlow,Google,Deep learning model building and deployment,Medium
1,Keras,Google / Keras Team,Easy neural network creation,Easy
2,JAX,Google,High-performance numerical computing and research,Medium to Hard
3,MXNet,Apache,Deep learning and scalable training,Medium


In [14]:
# ============================================================
# 12. FINAL OBSERVATION
# ============================================================

print("""
Observation:

1. TensorFlow is useful for building and deploying deep learning models.
2. Keras provides a simple high-level interface for creating neural networks.
3. JAX is useful for fast numerical computation and automatic differentiation.
4. MXNet supports tensor operations, gradients, and neural network development.

Conclusion:

In this experiment, we explored major deep learning libraries:
TensorFlow, Keras, JAX, and MXNet.
We performed tensor operations, built a simple neural network using Keras,
and demonstrated automatic differentiation using JAX and MXNet.
""")


Observation:

1. TensorFlow is useful for building and deploying deep learning models.
2. Keras provides a simple high-level interface for creating neural networks.
3. JAX is useful for fast numerical computation and automatic differentiation.
4. MXNet supports tensor operations, gradients, and neural network development.

Conclusion:

In this experiment, we explored major deep learning libraries:
TensorFlow, Keras, JAX, and MXNet.
We performed tensor operations, built a simple neural network using Keras,
and demonstrated automatic differentiation using JAX and MXNet.



In [15]:
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.10.0+cpu


In [16]:
# ============================================================
# 2. CHECK GPU AVAILABILITY
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using Device:", device)

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

Using Device: cpu


In [17]:
# ============================================================
# 3. BASIC TENSOR OPERATIONS
# ============================================================

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("Tensor A:")
print(a)

print("\nTensor B:")
print(b)

print("\nAddition:")
print(a + b)

print("\nMatrix Multiplication:")
print(torch.matmul(a, b))

Tensor A:
tensor([[1, 2],
        [3, 4]])

Tensor B:
tensor([[5, 6],
        [7, 8]])

Addition:
tensor([[ 6,  8],
        [10, 12]])

Matrix Multiplication:
tensor([[19, 22],
        [43, 50]])


In [18]:
# ============================================================
# 4. AUTOGRAD EXAMPLE
# ============================================================
# Autograd automatically calculates gradients.
# Gradients are used during backpropagation.

x = torch.tensor(4.0, requires_grad=True)

y = x**2 + 3*x + 5

y.backward()

print("Function value:", y.item())
print("Gradient dy/dx at x = 4:", x.grad.item())

Function value: 33.0
Gradient dy/dx at x = 4: 11.0


In [19]:
# ============================================================
# 5. SIMPLE NEURAL NETWORK FOR OR GATE
# ============================================================

# Input data
X = torch.tensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=torch.float32)

# Output labels
y = torch.tensor([
    [0],
    [1],
    [1],
    [1]
], dtype=torch.float32)

# Move data to GPU if available
X = X.to(device)
y = y.to(device)

In [20]:
# ============================================================
# 6. DEFINE MODEL
# ============================================================
# nn.Module is the base class for all neural networks in PyTorch.

class ORGateModel(nn.Module):
    def __init__(self):
        super(ORGateModel, self).__init__()

        # First hidden layer: 2 input neurons -> 4 hidden neurons
        self.hidden = nn.Linear(2, 4)

        # Output layer: 4 hidden neurons -> 1 output neuron
        self.output = nn.Linear(4, 1)

        # Activation function
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Forward pass
        x = self.hidden(x)
        x = self.relu(x)
        x = self.output(x)
        x = self.sigmoid(x)
        return x


model = ORGateModel().to(device)

print(model)

ORGateModel(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (output): Linear(in_features=4, out_features=1, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
)


In [21]:
# ============================================================
# 7. DEFINE LOSS FUNCTION AND OPTIMIZER
# ============================================================

# Binary Cross Entropy is used for binary classification
criterion = nn.BCELoss()

# Adam optimizer updates the model weights
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [22]:
# ============================================================
# 8. TRAIN THE MODEL
# ============================================================

epochs = 1000

for epoch in range(epochs):

    # Forward pass
    predictions = model(X)

    # Calculate loss
    loss = criterion(predictions, y)

    # Clear old gradients
    optimizer.zero_grad()

    # Backward pass: calculate new gradients
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss after every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [100/1000], Loss: 0.1559
Epoch [200/1000], Loss: 0.0296
Epoch [300/1000], Loss: 0.0116
Epoch [400/1000], Loss: 0.0062
Epoch [500/1000], Loss: 0.0039
Epoch [600/1000], Loss: 0.0027
Epoch [700/1000], Loss: 0.0019
Epoch [800/1000], Loss: 0.0015
Epoch [900/1000], Loss: 0.0012
Epoch [1000/1000], Loss: 0.0009


In [23]:
# ============================================================
# 9. TEST THE MODEL
# ============================================================

with torch.no_grad():
    predictions = model(X)

print("Predictions:")

for i in range(len(X)):
    input_value = X[i].cpu().numpy()
    predicted_value = predictions[i].item()
    final_output = round(predicted_value)

    print(input_value, "=>", final_output)

Predictions:
[0. 0.] => 0
[0. 1.] => 1
[1. 0.] => 1
[1. 1.] => 1


In [24]:
# ============================================================
# 10. FINAL OBSERVATION
# ============================================================

print("""
Observation:

1. PyTorch uses tensors for numerical computation.
2. It supports automatic differentiation using autograd.
3. Neural networks are created using nn.Module.
4. Loss functions measure prediction error.
5. Optimizers update weights during training.
6. PyTorch supports GPU acceleration using CUDA.

Conclusion:

In this experiment, we explored PyTorch by performing tensor operations,
automatic differentiation, and training a simple neural network for OR gate classification.
""")


Observation:

1. PyTorch uses tensors for numerical computation.
2. It supports automatic differentiation using autograd.
3. Neural networks are created using nn.Module.
4. Loss functions measure prediction error.
5. Optimizers update weights during training.
6. PyTorch supports GPU acceleration using CUDA.

Conclusion:

In this experiment, we explored PyTorch by performing tensor operations,
automatic differentiation, and training a simple neural network for OR gate classification.

